{
  "phases": {
    "install": {
      "cmds": [
        "npm ci"
      ]
    },
    "build": {
      "cmds": [
        "npx prisma generate",
        "npm run build"
      ]
    }
  },
  "start": {
    "cmd": "npm run start"
  }
}
